name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual deployment (optional)"
        required: false
        default: "Manual deploy to GitHub Pages"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --base-href /angular-basic/

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages \
            -d dist/ui \
            -r https://x-access-token:${GITHUB_TOKEN}@github.com/akhilkailas017/angular-basic.git